# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7208093afa4fd1d4cce31332bf0b3844e918a23a1efff73202b5dfef38a0e48fccf49d34ea588c055ae852534c85afea80cf9dfe5e4a2b7d609e117ba18f6e05

test:
  secret_key_base: b50fd4547cc1ef25d2394114d0ef057069e16a42b34afc7c21f20ec805bb724f97c9eb3d7e97bcb2a317550c53794698fbde79ab9623a7cfeb8314e90bcb2ad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
